services:
  - type: web
    name: ncufoodmap
    env: python
    rootDir: NCUFOODMAP_DJANGO
    buildCommand: pip install -r requirements.txt
    startCommand: >
      PYTHONPATH=$PYTHONPATH:. python manage.py migrate &&
      PYTHONPATH=$PYTHONPATH:. python manage.py collectstatic --noinput &&
      PYTHONPATH=$PYTHONPATH:. gunicorn ncufoodmap_backend.wsgi:application --bind 0.0.0.0:$PORT --log-level debug --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: sqlite3:///db.sqlite3
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: ncufoodmap_backend.settings
      - key: DEBUG
        value: False
      - key: DJANGO_ENV
        value: production
    autoDeploy: true 